resources:
  - url: http://127.0.0.1:5000/elapsed-time-card.js
    type: module
views:
  - cards:
      - type: custom:elapsed-time-card
        name: Time Elapsed Card
        entity: sun.sun
        test_gui: true
